import { Category, Recipe } from './models';

export const CATEGORIES: Category[] = [
  {
    id: 'snack',
    name: 'Snack',
    tagline: "Let's make something crunchy today!",
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=600&q=80',
  },
  {
    id: 'breakfast',
    name: 'Breakfast',
    tagline: "Let's start your day the tasty way!",
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80',
  },
  {
    id: 'lunch',
    name: 'Lunch',
    tagline: "Let's make some lunchtime favorites!",
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
  },
  {
    id: 'dinner',
    name: 'Dinner',
    tagline: "Let's make dinner unforgettable!",
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
  },
  {
    id: 'vegetarian',
    name: 'Vegetarian',
    tagline: "Let's make some green goodness!",
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
  },
  {
    id: 'vegan',
    name: 'Vegan',
    tagline: "Let's make some plant-based magic!",
    image: 'https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?w=600&q=80',
  },
  {
    id: 'japanese',
    name: 'Japanese',
    tagline: "Let's make some Asiatic vibes today!",
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
  },
  {
    id: 'italian',
    name: 'Italian',
    tagline: "Let's make some Italian magic!",
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=600&q=80',
  },
];

export const RECIPES: Recipe[] = [
  // Japanese
  {
    id: 'nigiri-sake',
    categoryId: 'japanese',
    name: 'Nigiri Sake',
    shortDesc: 'Very light and tasty traditional japanese food',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    difficulty: 'Very Hard',
    time: '40 Min',
    doses: 'Four People',
    cost: 'Very High',
    ingredients: [
      { name: 'Nishiki Rice', qty: '144g' },
      { name: 'Salmon Fillet', qty: '65g' },
      { name: 'Sea-Bass Fillet', qty: '40g' },
      { name: 'Tuna Fillet', qty: '50g' },
      { name: 'Ginger', qty: '6g' },
    ],
    instructions:
      'Before we make nigiri sushi, we need to prepare the sushi rice that will be used. Cook the Nishiki rice until sticky, season it with rice vinegar and let it cool to room temperature. Wet your hands, shape small oval mounds of rice, then lay a thin slice of fresh fish on top of each one, pressing gently so it sticks. Serve with soy sauce, pickled ginger and a dab of wasabi.',
  },
  {
    id: 'hosomaki-rolls',
    categoryId: 'japanese',
    name: 'Hosomaki Rolls',
    shortDesc: 'Variant of sushi rolled in nori seaweed',
    image: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?w=800&q=80',
    difficulty: 'Medium',
    time: '30 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Nishiki Rice', qty: '160g' },
      { name: 'Nori Seaweed', qty: '4 sheets' },
      { name: 'Cucumber', qty: '1' },
      { name: 'Salmon Fillet', qty: '50g' },
    ],
    instructions:
      'Lay a sheet of nori on a bamboo mat, spread a thin layer of seasoned rice over it leaving a border at the top. Place a strip of your chosen filling along the centre, then roll tightly using the mat. Slice into six even pieces with a wet, sharp knife.',
  },
  {
    id: 'temaki-rolls',
    categoryId: 'japanese',
    name: 'Temaki rolls',
    shortDesc: 'A hand rolled sushi wrapped in nori seaweed',
    image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80',
    difficulty: 'Low',
    time: '20 Min',
    doses: 'Two People',
    cost: 'Medium',
    ingredients: [
      { name: 'Nishiki Rice', qty: '120g' },
      { name: 'Nori Seaweed', qty: '4 sheets' },
      { name: 'Avocado', qty: '1' },
      { name: 'Salmon Fillet', qty: '60g' },
    ],
    instructions:
      'Hold a half sheet of nori in your palm, add a spoon of rice and spread it over one corner. Add your filling diagonally, then fold the nori around it into a cone. Enjoy immediately while the seaweed is still crisp.',
  },
  {
    id: 'uramaki-dragon',
    categoryId: 'japanese',
    name: 'Uramaki Dragon',
    shortDesc: 'A hand rolled sushi wrapped in nori seaweed',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80',
    difficulty: 'Hard',
    time: '45 Min',
    doses: 'Four People',
    cost: 'High',
    ingredients: [
      { name: 'Nishiki Rice', qty: '180g' },
      { name: 'Nori Seaweed', qty: '4 sheets' },
      { name: 'Eel', qty: '80g' },
      { name: 'Avocado', qty: '1' },
      { name: 'Sesame Seeds', qty: '10g' },
    ],
    instructions:
      'Roll the rice on the outside of the nori this time, wrapping it in cling film to keep it from sticking. Fill with eel and cucumber, roll tightly, then top with thin avocado slices fanned out like dragon scales and a sprinkle of sesame seeds.',
  },
  {
    id: 'sashimi-mix',
    categoryId: 'japanese',
    name: 'Sashimi Mix',
    shortDesc: 'Simple and tasty sushi dish without rice',
    image: 'https://images.unsplash.com/photo-1584583570840-0a3d88497e46?w=800&q=80',
    difficulty: 'Low',
    time: '15 Min',
    doses: 'Two People',
    cost: 'High',
    ingredients: [
      { name: 'Salmon Fillet', qty: '80g' },
      { name: 'Tuna Fillet', qty: '80g' },
      { name: 'Sea-Bass Fillet', qty: '60g' },
      { name: 'Daikon Radish', qty: '30g' },
    ],
    instructions:
      'Make sure your fish is sushi-grade and very cold. With a sharp knife, slice it against the grain into thin even pieces. Arrange over shredded daikon and serve with soy sauce and wasabi on the side.',
  },
  {
    id: 'traditional-mochi',
    categoryId: 'japanese',
    name: 'Traditional Mochi',
    shortDesc: 'A soft rice cake filled with sweet bean paste',
    image: 'https://images.unsplash.com/photo-1631206753348-db44968fd440?w=800&q=80',
    difficulty: 'Medium',
    time: '50 Min',
    doses: 'Six People',
    cost: 'Low',
    ingredients: [
      { name: 'Glutinous Rice Flour', qty: '200g' },
      { name: 'Sugar', qty: '50g' },
      { name: 'Water', qty: '240ml' },
      { name: 'Red Bean Paste', qty: '150g' },
      { name: 'Potato Starch', qty: '30g' },
    ],
    instructions:
      'Whisk the rice flour, sugar and water together and steam for around 20 minutes, stirring halfway through. Dust your work surface with potato starch, portion the warm dough, flatten each piece and wrap it around a small ball of red bean paste.',
  },

  // Vegan
  {
    id: 'avocado-toast',
    categoryId: 'vegan',
    name: 'Avocado Toast',
    shortDesc: 'A bright breakfast toast, three delicious ways',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80',
    difficulty: 'Very Low',
    time: '15 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Sourdough Bread', qty: '4 slices' },
      { name: 'Avocado', qty: '2' },
      { name: 'Cherry Tomatoes', qty: '100g' },
      { name: 'Banana', qty: '1' },
      { name: 'Blueberries', qty: '50g' },
    ],
    instructions:
      'Toast the bread until golden. Mash one avocado with a pinch of salt and lemon juice and spread it thick on a slice, then top with cherry tomato halves. Slice the remaining avocado thin, fan over a second slice with banana and blueberries for a sweet twist.',
  },
  {
    id: 'bruschetta',
    categoryId: 'vegan',
    name: 'Bruschetta',
    shortDesc: 'Toasted bread topped with fresh tomato and basil',
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&q=80',
    difficulty: 'Low',
    time: '15 Min',
    doses: 'Four People',
    cost: 'Low',
    ingredients: [
      { name: 'Baguette', qty: '1' },
      { name: 'Tomatoes', qty: '4' },
      { name: 'Basil', qty: '10 leaves' },
      { name: 'Garlic', qty: '1 clove' },
      { name: 'Olive Oil', qty: '30ml' },
    ],
    instructions:
      'Dice the tomatoes and mix with chopped basil, olive oil, salt and pepper. Toast slices of baguette, rub each one with the cut side of a garlic clove while still warm, then top generously with the tomato mixture.',
  },
  {
    id: 'soy-burger',
    categoryId: 'vegan',
    name: 'Soy Burger',
    shortDesc: 'A plant-based burger packed with flavour',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    difficulty: 'Medium',
    time: '35 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Soy Patties', qty: '4' },
      { name: 'Burger Buns', qty: '4' },
      { name: 'Lettuce', qty: '4 leaves' },
      { name: 'Red Onion', qty: '1' },
      { name: 'Vegan Mayo', qty: '40g' },
    ],
    instructions:
      'Pan-fry the soy patties for about four minutes per side until browned. Toast the buns lightly, spread with vegan mayo, then build the burger with lettuce, patty and thin rings of red onion.',
  },
  {
    id: 'mediterranean-salad',
    categoryId: 'vegan',
    name: 'Mediterranean Salad',
    shortDesc: 'A refreshing mix of crisp vegetables and herbs',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
    difficulty: 'Very Low',
    time: '10 Min',
    doses: 'Two People',
    cost: 'Low',
    ingredients: [
      { name: 'Cucumber', qty: '1' },
      { name: 'Tomatoes', qty: '3' },
      { name: 'Red Onion', qty: '1/2' },
      { name: 'Olives', qty: '60g' },
      { name: 'Olive Oil', qty: '20ml' },
    ],
    instructions:
      'Chop the cucumber, tomatoes and onion into bite-size pieces, toss with olives, a good drizzle of olive oil, salt and oregano. Let it rest for a few minutes before serving so the flavours mingle.',
  },
  {
    id: 'avocado-tacos',
    categoryId: 'vegan',
    name: 'Avocado Tacos',
    shortDesc: 'Soft tacos loaded with creamy avocado and veg',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&q=80',
    difficulty: 'Low',
    time: '20 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Corn Tortillas', qty: '8' },
      { name: 'Avocado', qty: '2' },
      { name: 'Black Beans', qty: '200g' },
      { name: 'Red Cabbage', qty: '100g' },
      { name: 'Lime', qty: '1' },
    ],
    instructions:
      'Warm the tortillas in a dry pan. Fill each one with black beans, sliced avocado and shredded red cabbage, then finish with a squeeze of lime and a pinch of chilli flakes.',
  },
  {
    id: 'potato-salad',
    categoryId: 'vegan',
    name: 'Potato Salad',
    shortDesc: 'A hearty side dish with a tangy herb dressing',
    image: 'https://images.unsplash.com/photo-1568158879083-c42860933ed7?w=800&q=80',
    difficulty: 'Low',
    time: '30 Min',
    doses: 'Four People',
    cost: 'Low',
    ingredients: [
      { name: 'Potatoes', qty: '600g' },
      { name: 'Dijon Mustard', qty: '20g' },
      { name: 'Chives', qty: '10g' },
      { name: 'Olive Oil', qty: '30ml' },
    ],
    instructions:
      'Boil the potatoes whole until fork-tender, then cool slightly and cut into chunks. Whisk mustard, olive oil, salt and pepper together, pour over the warm potatoes and finish with chopped chives.',
  },

  // Breakfast
  {
    id: 'chocolate-muffin',
    categoryId: 'breakfast',
    name: 'Chocolate Muffin',
    shortDesc: 'Soft and rich muffins with melted chocolate chunks',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80',
    difficulty: 'Low',
    time: '35 Min',
    doses: 'Six People',
    cost: 'Low',
    ingredients: [
      { name: 'Flour', qty: '250g' },
      { name: 'Cocoa Powder', qty: '30g' },
      { name: 'Dark Chocolate', qty: '100g' },
      { name: 'Eggs', qty: '2' },
      { name: 'Butter', qty: '80g' },
    ],
    instructions:
      'Mix the dry ingredients, then fold in melted butter, eggs and chopped dark chocolate until just combined. Divide between muffin cases and bake at 180°C for about 20 minutes.',
  },
  {
    id: 'berry-pancakes',
    categoryId: 'breakfast',
    name: 'Berry Pancakes',
    shortDesc: 'Fluffy pancakes stacked with fresh seasonal berries',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    difficulty: 'Low',
    time: '25 Min',
    doses: 'Four People',
    cost: 'Low',
    ingredients: [
      { name: 'Flour', qty: '200g' },
      { name: 'Milk', qty: '300ml' },
      { name: 'Eggs', qty: '2' },
      { name: 'Mixed Berries', qty: '150g' },
      { name: 'Maple Syrup', qty: '40ml' },
    ],
    instructions:
      'Whisk flour, milk and eggs into a smooth batter. Cook small rounds in a lightly buttered pan until bubbles form, then flip. Stack and top with berries and a drizzle of maple syrup.',
  },
  {
    id: 'overnight-oats',
    categoryId: 'breakfast',
    name: 'Overnight Oats',
    shortDesc: 'A creamy make-ahead breakfast with fruit and nuts',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&q=80',
    difficulty: 'Very Low',
    time: '5 Min',
    doses: 'One Person',
    cost: 'Low',
    ingredients: [
      { name: 'Rolled Oats', qty: '50g' },
      { name: 'Milk', qty: '150ml' },
      { name: 'Greek Yogurt', qty: '50g' },
      { name: 'Honey', qty: '15ml' },
      { name: 'Almonds', qty: '20g' },
    ],
    instructions:
      'Stir the oats, milk, yogurt and honey together in a jar, cover and refrigerate overnight. In the morning top with sliced almonds and fresh fruit before serving.',
  },

  // Lunch
  {
    id: 'cheeseburger',
    categoryId: 'lunch',
    name: 'Cheeseburger',
    shortDesc: 'A juicy classic burger with melted cheddar',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    difficulty: 'Medium',
    time: '25 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Beef Patties', qty: '4' },
      { name: 'Cheddar Cheese', qty: '4 slices' },
      { name: 'Burger Buns', qty: '4' },
      { name: 'Lettuce', qty: '4 leaves' },
      { name: 'Tomatoes', qty: '1' },
    ],
    instructions:
      'Season the patties and sear over high heat for three minutes per side, adding cheese in the last minute so it melts. Toast the buns and build your burger with lettuce, tomato and all the sauces you like.',
  },
  {
    id: 'caesar-salad',
    categoryId: 'lunch',
    name: 'Caesar Salad',
    shortDesc: 'Crisp romaine with parmesan and a creamy dressing',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&q=80',
    difficulty: 'Low',
    time: '20 Min',
    doses: 'Two People',
    cost: 'Medium',
    ingredients: [
      { name: 'Romaine Lettuce', qty: '1 head' },
      { name: 'Parmesan', qty: '40g' },
      { name: 'Croutons', qty: '60g' },
      { name: 'Caesar Dressing', qty: '50g' },
    ],
    instructions:
      'Tear the romaine into a large bowl, toss with the dressing until every leaf is coated, then scatter over croutons and shaved parmesan just before serving.',
  },
  {
    id: 'grilled-chicken-bowl',
    categoryId: 'lunch',
    name: 'Grilled Chicken Bowl',
    shortDesc: 'A balanced bowl with grains, greens and grilled chicken',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    difficulty: 'Medium',
    time: '30 Min',
    doses: 'Two People',
    cost: 'Medium',
    ingredients: [
      { name: 'Chicken Breast', qty: '2' },
      { name: 'Quinoa', qty: '150g' },
      { name: 'Spinach', qty: '80g' },
      { name: 'Cherry Tomatoes', qty: '100g' },
    ],
    instructions:
      'Grill the seasoned chicken breasts for six minutes per side, then slice. Serve over cooked quinoa with fresh spinach and cherry tomatoes, finished with a squeeze of lemon.',
  },

  // Dinner
  {
    id: 'pumpkin-rice',
    categoryId: 'dinner',
    name: 'Pumpkin Rice',
    shortDesc: 'A comforting creamy rice with roasted pumpkin',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80',
    difficulty: 'Medium',
    time: '40 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Arborio Rice', qty: '300g' },
      { name: 'Pumpkin', qty: '400g' },
      { name: 'Vegetable Stock', qty: '1L' },
      { name: 'Parmesan', qty: '50g' },
    ],
    instructions:
      'Roast the diced pumpkin until soft, then mash half of it. Toast the rice, add the stock a ladle at a time while stirring, folding in the pumpkin halfway through. Finish with parmesan.',
  },
  {
    id: 'herb-roasted-chicken',
    categoryId: 'dinner',
    name: 'Herb Roasted Chicken',
    shortDesc: 'A whole roasted chicken with garden herbs',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80',
    difficulty: 'Hard',
    time: '90 Min',
    doses: 'Six People',
    cost: 'High',
    ingredients: [
      { name: 'Whole Chicken', qty: '1.5kg' },
      { name: 'Rosemary', qty: '2 sprigs' },
      { name: 'Thyme', qty: '2 sprigs' },
      { name: 'Garlic', qty: '4 cloves' },
      { name: 'Butter', qty: '60g' },
    ],
    instructions:
      'Rub the chicken all over with softened herb butter and stuff the cavity with garlic and herb sprigs. Roast at 200°C for around 80 minutes, basting halfway through, and rest before carving.',
  },

  // Vegetarian
  {
    id: 'avocado-salad',
    categoryId: 'vegetarian',
    name: 'Avocado Salad',
    shortDesc: 'A light salad with creamy avocado and citrus',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
    difficulty: 'Very Low',
    time: '10 Min',
    doses: 'Two People',
    cost: 'Low',
    ingredients: [
      { name: 'Avocado', qty: '2' },
      { name: 'Rocket', qty: '60g' },
      { name: 'Orange', qty: '1' },
      { name: 'Pumpkin Seeds', qty: '20g' },
    ],
    instructions:
      'Slice the avocado and orange segments over a bed of rocket, scatter with pumpkin seeds and dress lightly with olive oil, salt and pepper.',
  },
  {
    id: 'veggie-stir-fry',
    categoryId: 'vegetarian',
    name: 'Veggie Stir Fry',
    shortDesc: 'A colourful wok of crunchy seasonal vegetables',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    difficulty: 'Low',
    time: '20 Min',
    doses: 'Two People',
    cost: 'Low',
    ingredients: [
      { name: 'Broccoli', qty: '150g' },
      { name: 'Carrot', qty: '2' },
      { name: 'Bell Pepper', qty: '1' },
      { name: 'Soy Sauce', qty: '30ml' },
      { name: 'Ginger', qty: '10g' },
    ],
    instructions:
      'Heat a wok until smoking, add the hardest vegetables first and toss constantly. Add ginger and soy sauce towards the end so nothing burns, and serve immediately over rice.',
  },
  {
    id: 'caprese-salad',
    categoryId: 'vegetarian',
    name: 'Caprese Salad',
    shortDesc: 'Fresh mozzarella, tomato and basil, Italian style',
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800&q=80',
    difficulty: 'Very Low',
    time: '10 Min',
    doses: 'Two People',
    cost: 'Medium',
    ingredients: [
      { name: 'Buffalo Mozzarella', qty: '200g' },
      { name: 'Tomatoes', qty: '3' },
      { name: 'Basil', qty: '10 leaves' },
      { name: 'Olive Oil', qty: '20ml' },
    ],
    instructions:
      'Slice the mozzarella and tomatoes into even rounds and layer them alternately on a plate. Tuck basil leaves between the layers and finish with olive oil, salt and a crack of pepper.',
  },

  // Italian
  {
    id: 'margherita-pizza',
    categoryId: 'italian',
    name: 'Margherita Pizza',
    shortDesc: 'The classic pizza with tomato, mozzarella and basil',
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=800&q=80',
    difficulty: 'Medium',
    time: '50 Min',
    doses: 'Two People',
    cost: 'Low',
    ingredients: [
      { name: 'Pizza Dough', qty: '1'},
      { name: 'Tomato Sauce', qty: '120g' },
      { name: 'Mozzarella', qty: '150g' },
      { name: 'Basil', qty: '8 leaves' },
    ],
    instructions:
      'Stretch the dough into a round, spread with tomato sauce leaving a border for the crust, then scatter torn mozzarella on top. Bake at the highest oven temperature until the crust blisters, and finish with fresh basil.',
  },
  {
    id: 'pesto-pasta',
    categoryId: 'italian',
    name: 'Pesto Pasta',
    shortDesc: 'A quick pasta tossed in fresh basil pesto',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    difficulty: 'Low',
    time: '20 Min',
    doses: 'Four People',
    cost: 'Medium',
    ingredients: [
      { name: 'Trofie Pasta', qty: '400g' },
      { name: 'Basil', qty: '60g' },
      { name: 'Pine Nuts', qty: '30g' },
      { name: 'Parmesan', qty: '50g' },
      { name: 'Olive Oil', qty: '80ml' },
    ],
    instructions:
      'Blend basil, pine nuts, parmesan, olive oil and a pinch of salt into a smooth pesto. Cook the pasta until al dente, then toss straight into the pesto with a splash of the cooking water to loosen it.',
  },

  // Snack
  {
    id: 'veggie-toast-platter',
    categoryId: 'snack',
    name: 'Veggie Toast Platter',
    shortDesc: 'Mini toasts topped with fresh crunchy vegetables',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80',
    difficulty: 'Very Low',
    time: '15 Min',
    doses: 'Four People',
    cost: 'Low',
    ingredients: [
      { name: 'Rye Bread', qty: '6 slices' },
      { name: 'Cream Cheese', qty: '100g' },
      { name: 'Radish', qty: '4' },
      { name: 'Cucumber', qty: '1' },
    ],
    instructions:
      'Toast the bread, spread with cream cheese, then top with thin slices of radish and cucumber. Finish with a sprinkle of black sesame or fresh herbs.',
  },
  {
    id: 'hummus-crackers',
    categoryId: 'snack',
    name: 'Hummus & Crackers',
    shortDesc: 'A smooth chickpea dip with crunchy crackers',
    image: 'https://images.unsplash.com/photo-1615937722923-67f6deaf2cc9?w=800&q=80',
    difficulty: 'Very Low',
    time: '10 Min',
    doses: 'Four People',
    cost: 'Low',
    ingredients: [
      { name: 'Chickpeas', qty: '240g' },
      { name: 'Tahini', qty: '30g' },
      { name: 'Lemon', qty: '1' },
      { name: 'Garlic', qty: '1 clove' },
      { name: 'Olive Oil', qty: '30ml' },
    ],
    instructions:
      'Blend the chickpeas, tahini, lemon juice, garlic and olive oil until smooth, adding a splash of water if needed. Drizzle with more olive oil and serve with crackers or vegetable sticks.',
  },
];

export const NEW_RECIPE_IDS = ['chocolate-muffin', 'pumpkin-rice', 'cheeseburger', 'avocado-salad', 'margherita-pizza', 'nigiri-sake'];
